# Generated by Django 2.2.4 on 2019-10-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191011_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(max_length=50)),
                ('start_location', models.CharField(max_length=50)),
                ('end_location', models.CharField(max_length=50)),
                ('start_time', models.CharField(max_length=50)),
                ('end_time', models.CharField(max_length=50)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('passengers1', models.CharField(default=None, max_length=50)),
                ('passengers2', models.CharField(default=None, max_length=50)),
                ('passengers3', models.CharField(default=None, max_length=50)),
                ('passengers4', models.CharField(default=None, max_length=50)),
                ('passengers5', models.CharField(default=None, max_length=50)),
                ('passengers6', models.CharField(default=None, max_length=50)),
                ('distance', models.IntegerField()),
                ('fare', models.IntegerField()),
                ('CO2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RideSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('user_type', models.CharField(max_length=50)),
                ('nop', models.CharField(max_length=50)),
                ('start_location', models.CharField(max_length=50)),
                ('end_location', models.CharField(max_length=50)),
                ('start_time', models.CharField(max_length=50)),
                ('end_time', models.CharField(max_length=50)),
            ],
        ),
    ]
