# Generated by Django 2.2.4 on 2019-10-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_ride_ridesetup'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='fare_saved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
