# Generated by Django 2.2.4 on 2019-11-20 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
